# reproducibility
deterministic: False
random_seed: 42

# precision
fp16: False

training:
  epochs: 1
  warmup_steps: 0
  max_steps: 10
evaluation:
  steps: 10  # should be the same as save_steps in logging
  evaluation_strategy: steps

max_grad_norm: 1